### ISSUE TITLE
embedder.pt with new dataset

### ISSUE THREAD

**Issue by Devid29** [mindslab-ai/voicefilter#19]
Hi, if in case I wanted to use another dataset of audio files for the training and the test (not the one used here) the embedder.pt that I have to insert when I run "trainer.py" as I can generate it or which one I have to use ? Thank you

**Comment by seungwonpark** [comment]
Generally, you can simply use the provided embedder.pt for all cases. Since the speaker vector extractor was trained on VoxCeleb2 dataset, it works well with various language/environments.

Seung-won Park
Undergraduate Student
Dept. of Physics and Astronomy & Computer Science Engineering
Seoul National University
yyyyy@snu.ac.kr | http://swpark.me
________________________________

**Comment by seungwonpark** [comment]
Yes, there were no significant problem when I was trying to use it with Korean speech. Good luck on your testing with Italian speech!

Best, Seungwon

**Comment by Devid29** [comment]
Thank you!
